community/urls.py
from . import views
from django.urls import path, re_path


app_name = 'community'

urlpatterns = [
    path('community/', views.home, name='home'),
    path('savequestion/', views.savequestion, name='savequestion'),
    re_path(r'^saveanswer/(?P<questionid>[0-9]+)$', views.saveanswer, name='saveanswer'),
]

django1/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from library import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('', include('library.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('', include('community.urls')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/urls.py
from django.urls import path, re_path
from . import views

app_name = 'library'

urlpatterns = [
    path('', views.index, name='index'),

    path('books/', views.BookListView.as_view(), name='BookList'),
    path('books/<int:pk>', views.BookDetailView.as_view(), name='BookDetail'),

    path('authors/', views.AuthorListView.as_view(), name='AuthorList'),
    path('authors/<int:pk>', views.AuthorDetailView.as_view(), name='AuthorDetail'),

    path('categories/', views.CategoryListView, name='CategoryList'),
    path('categories/<int:pk>', views.CategoryDetailView.as_view(), name='CategoryDetail'),

    path('follow/', views.follow, name="follow"),
    path('unfollow/', views.unfollow, name="unfollow"),

    path('add_to_wishlist/', views.add_to_wishlist, name="add_to_wishlist"),
    path('remove_from_wishlist/', views.remove_from_wishlist, name="remove_from_wishlist"),

    re_path(r'^favourite', views.favourite, name='favBook'),
    re_path(r'^delFav', views.deleteFav, name='delfavBook'),
    re_path(r'^deleteRead', views.deleteRead, name='delreadBook'),
    re_path(r'^rate', views.rate, name='rate'),
    path('read/', views.read, name='read'),
    path('unread/', views.deleteRead, name='deleteRead'),
    re_path(r'^favCat', views.favCat, name='favCat'),
    re_path(r'^delCat', views.deleteCat, name='delCat'),


]

users/urls.py
from django.urls import path, re_path, include
from . import views
from django.contrib.auth import views as view

app_name = 'user'

urlpatterns = [
    re_path(r'^signup/$', views.sign_up, name='signup'),  # signup.
    re_path(r'^$', views.home, name='home'),
    re_path(r'^login/$', views.log_in, name='login'),
    re_path('logout', view.logout, {'next_page': 'login'}, name='logout'),
    re_path(r'^profile/(?P<Username>\w+)/$', views.profile, name='profile'),  # show other users profile.
    re_path(r'^search', views.search, name='search'),

]

templates/general_view/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

     <title>{% block title %}Library{% endblock %}</title>
    {% load staticfiles %}

     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
     <link href="{% static 'css/rtl.css' %}" rel="stylesheet">
     <link href="{% static 'css/style.css' %}" rel="stylesheet">
     <link href="{% static 'css/fontawesome-all.min.css' %}" rel="stylesheet">
{% block st %}
{% endblock %}

  </head>
  <body>
  <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'library:index' %}"><img src="{% static 'img/3.PNG' %}" width="70" height="70"/></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'library:AuthorList' %}">Authors <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'library:CategoryList' %}">Categories</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'library:BookList' %}">Books</a>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'community:home' %}">Community</a>
            </li>
        {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'user:search' %}" method="get" accept-charset="utf-8" >

      {% if user.is_authenticated %}
        <input class="form-control mr-sm-2" type="text"  placeholder="Search" aria-label="Search" name="search">
        <button class="btn btn-outline-warning" type="submit">Search</button>/
        <a class="btn btn-outline-warning" href="{% url 'user:home' %}"> Profile</a>
        <a class="btn btn-outline-warning" href="{% url 'logout' %}">logout</a>
      {% else %}
        <a  class="btn btn-outline-warning" href="{% url 'login' %}">login</a> /
        <a  class="btn btn-outline-warning" href="{% url 'user:signup' %}">signup</a>
      {% endif %}

    </form>
  </div>
</nav>
    <main>
      {% block content %}
      {% endblock %}
    </main>
  <br><br><br><br>
  <section class="footer">
      <div class="container">
        <div class="row">
            <div class="col-lg-6">
             <h4 class="text-center">What we offer ?</h4>
            </div>

            <div class="col-lg-6">
                <h4 class="text-center">Contact Us.</h4>
            </div>

        </div>
      </div>
      <div class="copy text-center">
          copyrights &copy; <span> reads.com</span>
      </div>
  </section>

   <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
   <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
   <script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block js-foot %}
{% endblock %}
  </body>
</html>

templates/general_view/home.html
{% extends 'general_view/base.html' %}

{% load staticfiles %}
{% block content %}
    <br><br>
    <center><h2>{{user.username}}'s Profile.</h2></center>
    <br><br><br><br>
    <div class="img">
        {% if user.profile.picture %}
            <img src="{{ user.profile.picture.url }}" alt="can't load image" width="160" class="img-responsive img-circle mt mb profileimg">
        {% endif %}
        <p>&nbsp;&nbsp;&nbsp;&nbsp;  Username: &nbsp;&nbsp;&nbsp;&nbsp;{{user.username}}<br></p>
        <p>&nbsp;&nbsp;&nbsp;&nbsp;  Name: &nbsp;&nbsp;&nbsp;&nbsp;{{ user.first_name }} {{ user.last_name }}<br></p>
        <p>&nbsp;&nbsp;&nbsp;&nbsp;  Email: &nbsp;&nbsp;&nbsp;&nbsp;{{ user.email }}<br></p>
        <p>&nbsp;&nbsp;&nbsp;&nbsp; birth date: &nbsp;&nbsp;&nbsp;&nbsp;{{ user.profile.birth_date }}<br></p>
    <br><br><br><br>


    <p></p>
    </div>
    {%if booklist %}
        <br><br><br>
        <center><h2>WishList.</h2></center>
        <br><br><br>
        <p></p>
        <div class="catindex">
            {%for book in booklist%}
                <a href="{% url 'library:BookDetail' book.pk %}">
                    <img  src="{{ book.picture.url }}" alt="can't load image" width="160" >
                </a>
        &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
            {%endfor%}
        </div>
        <br><br>
    {%endif%}

    <p></p>
    {%if followlist %}
        <br><br><br>
        <center><h2>Followed Authors.</h2></center>
        <br><br><br>
        <p></p>
        <div class="catindex">
            {%for author in followlist%}
                <a href="{% url 'library:AuthorDetail' author.pk %}">
                    <img style=float-left; src="{{ author.picture.url }}" alt="can't load image" width="160" >
                </a>
        &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
            {%endfor%}
        </div>
        <br><br>
    {%endif%}

    <p></p>
    {%if readlist %}
        <br><br><br>
        <center><h2>Marked as read.</h2></center>
        <br><br><br>
        <p></p>
        <div class="catindex">
            {%for book in readlist%}
            <a href="{% url 'library:BookDetail' book.pk %}">
                    <img style=float-left; src="{{ book.picture.url }}" alt="can't load image" width="160">
                </a>
        &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
            {%endfor%}
        </div>
        <br><br>
    {%endif%}

    <p></p>
    {%if favcategorylist %}
        <br><br><br>
        <center><h2>Favourite Categories.</h2></center>
        <br><br><br>
        <p></p>
        <div class="catindex">
            {%for category in favcategorylist%}
                <a href="{% url 'library:CategoryDetail' category.pk %}">
                    <img style=float-left; src="{{ category.picture.url }}" alt="can't load image" width="160">
                </a>
        &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
            {%endfor%}
        </div>
        <br><br>
    {%endif%}

    <p></p>
    {%if favbooklist %}
        <br><br><br>
        <center><h2>Favourite Books.</h2></center>
        <br><br><br>
        <p></p>
        <div class="catindex">
            {%for book in favbooklist%}
                <a href="{% url 'library:BookDetail' book.pk %}">
                    <img style=float-left; src="{{ book.picture.url }}" alt="can't load image" width="160">
                </a>
        &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
            {%endfor%}
        </div>
        <br><br>
    {%endif%}

    <p></p>
    {%if recommend_author %}
        <br><br><br>
        <center><h2>Recommended Authors.</h2></center>
        <br><br><br>
        <p></p>
        <div class="catindex">
            {%for r in recommend_author%}
                <a href="{% url 'library:AuthorDetail' r.pk %}">
                    <img style=float-left; src="{{ r.picture.url }}" alt="can't load image" width="160" >
                </a>
        &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
            {%endfor%}
        </div>
        <br><br>
    {%endif%}

    <p></p>
    {%if recommend_book %}
        <br><br><br>
        <center><h2>Recommended Books.</h2></center>
        <br><br><br>
        <p></p>
        <div class="catindex">
            {%for r in recommend_book%}
                <a href="{% url 'library:BookDetail' r.pk %}">
                    <img style=float-left; src="{{ r.picture.url }}" alt="can't load image" width="160">
                </a>
        &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
            {%endfor%}
        </div>
        <br><br>
    {%endif%}

    <p></p>
    {%if recommend_category %}
        <br><br><br>
        <center><h2>Recommended Categories.</h2></center>
        <br><br><br>
        <p></p>
        <div class="catindex">
            {%for r in recommend_category%}
                <a href="{% url 'library:CategoryDetail' r.pk %}">
                    <img style=float-left; src="{{ r.picture.url }}" alt="can't load image" width="160">
                </a>
        &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
            {%endfor%}
        </div>
        <br><br>
    {%endif%}

{% endblock %}

templates/general_view/signup.html
{% extends 'general_view/base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <br><br>
            <center><h2>Sign up</h2></center>
            <br><br><br><br>
        </div>
        <div class="signup">
            <form action="." method="post" accept-charset="utf-8" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    <div class="row">
                        <div class="col-lg-4">
                            <p> {{ field.label_tag }}</p><br>
                        </div>
                        <div class="col-lg-8">
                            <label  > {{ field }}</label><br>
                        </div>
                    </div>
                {% for error in field.errors %}
                  <p style="color: red">{{ error }}</p>
                {% endfor %}
                {% endfor %}
                <br><br>
                <button type="submit" class="btn btn-outline-warning signupbtn">Register</button>
                <p></p>
            </form>
        </div>
    </div>
</div>
<br><br><br><br>
{% endblock %}