django1/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from library import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('', include('library.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('', include('community.urls')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/urls.py
from django.urls import path, re_path
from . import views

app_name = 'library'

urlpatterns = [
    path('', views.index, name='index'),

    path('books/', views.BookListView.as_view(), name='BookList'),
    path('books/<int:pk>', views.BookDetailView.as_view(), name='BookDetail'),

    path('authors/', views.AuthorListView.as_view(), name='AuthorList'),
    path('authors/<int:pk>', views.AuthorDetailView.as_view(), name='AuthorDetail'),

    path('categories/', views.CategoryListView, name='CategoryList'),
    path('categories/<int:pk>', views.CategoryDetailView.as_view(), name='CategoryDetail'),

    path('follow/', views.follow, name="follow"),
    path('unfollow/', views.unfollow, name="unfollow"),

    path('add_to_wishlist/', views.add_to_wishlist, name="add_to_wishlist"),
    path('remove_from_wishlist/', views.remove_from_wishlist, name="remove_from_wishlist"),

    re_path(r'^favourite', views.favourite, name='favBook'),
    re_path(r'^delFav', views.deleteFav, name='delfavBook'),
    re_path(r'^deleteRead', views.deleteRead, name='delreadBook'),
    re_path(r'^rate', views.rate, name='rate'),
    path('read/', views.read, name='read'),
    path('unread/', views.deleteRead, name='deleteRead'),
    re_path(r'^favCat', views.favCat, name='favCat'),
    re_path(r'^delCat', views.deleteCat, name='delCat'),


]

users/urls.py
from django.urls import path, re_path, include
from . import views
from django.contrib.auth import views as view

app_name = 'user'

urlpatterns = [
    re_path(r'^signup/$', views.sign_up, name='signup'),  # signup.
    re_path(r'^$', views.home, name='home'),
    re_path(r'^login/$', views.log_in, name='login'),
    re_path('logout', view.logout, {'next_page': 'login'}, name='logout'),
    re_path(r'^profile/(?P<Username>\w+)/$', views.profile, name='profile'),  # show other users profile.
    re_path(r'^search', views.search, name='search'),

]

templates/library_view/author_detail.html
{% extends 'general_view/base.html' %}
{% load staticfiles %}
{% block content %}
{%if author%}
<div class="col-lg-12 col-md-12 text-center">
        <br><br>
        <center><h2>{{author.name}}</h2></center>
        <br><br><br><br>
</div>
 <div class="container">
     <div class="row">
         <div class="col-lg-12">
             <div class="row">
                 <div class="col-lg-3">
                     <img src="{{ author.picture.url }}"  alt="can't load image" width="160" height="170" class="img-responsive img-circle mt mb">
                 </div>
                 <div class="col-lg-9">
                     <p>Born at:<a class="fontcolor"> {{author.born_at}}</a></p>
                     <p>Died at:  <a>{{author.died_at}}</a></p>
                     <p>Contact: {{author.contact}}</p>
                     <p class="lead">Bio: <a class="writing">{{author.bio}}</a></p>
                 </div>
             </div>
         </div>
         <div class="follow">
        {% if user.is_authenticated%}
            {% if status == False %}
                <form method="POST" action="{% url 'library:follow' %}">
                    {% csrf_token %}
                    <input class="btn btn-outline-warning" type="submit"   name="follow" value="Follow" />
                    <input class="btn btn-outline-warning" type="hidden" name="author_id" value="{{author.author_id}}" />
                </form>
            {% endif%}
            {% if status == True %}
                <form method="POST" action="{% url 'library:unfollow' %}">
                    {% csrf_token %}
                    <input class="btn btn-outline-warning" type="submit"  name="unfollow" value="unFollow" />
                    <input class="btn btn-outline-warning" type="hidden" name="author_id" value="{{author.author_id}}" />
                </form>
            {% endif%}
        {% endif%}
    </div>
         {%if mybooks%}
             <div class="col-lg-12">
                 <p></p>
                 <p></p>
                    <center><h2>Books</h2></center>
                 <p></p>
                 {% for book in mybooks %}
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-12 col-lg-offset-3 col-md-12 ">
                                <img src="{{ book.picture.url }}" alt="can't load image" width="160" height="170" class="img-responsive img-circle mt mb">
                                <pre></pre>
                                <a href="{% url 'library:BookDetail' book.pk %}">{{ book.name}}</a>
                                <pre></pre>
                                <pre></pre>
                            </div>
                        </div>
                    </div>
                 {% endfor %}
             </div>
         {%else%}
   </div>
</div>
            <div class=""><center><h2>There're no books yet.</h2></center></div>
            <br><br><br><br>
            <center><img src="{% static 'img/sad.png' %}"  height="300" width="300" /></center>
        {% endif %}

<pre>

</pre>
{% else%}

<div class=""><center><h2>Something went wrong.</h2></center></div>
<center><img src="{% static 'img/error.png' %}"  height="150" width="150"/></center>
{%endif%}
{% endblock %}

templates/library_view/author_list.html
{% extends 'general_view/base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="col-lg-12 col-md-12 text-center">
        <br><br>
        <center><h2>Authors.</h2></center>
        <br><br><br><br>
    </div>
{% if author_list %}
    {% for author in author_list%}
    <div class="container">
        <div class="row">
              <div class="col-lg-12 col-lg-offset-3 col-md-12 ">
                  <img src="{{ author.picture.url }}" alt="can't load image" width="160" height="170" class="img-responsive img-circle mt mb">
                  <pre></pre>
                  <a href="{% url 'library:AuthorDetail' author.pk %}">{{ author.name}}</a>
                  <pre></pre>
                  <pre></pre>
              </div>
        </div>
    </div>
    {% endfor %}
{% else %}
<br><br><br><br>
<div class=""><center><h2>There're no authors yet.</h2></center></div>
<br><br><br><br>
<center><img src="{% static 'img/sad.png' %}"  height="300" width="300" /></center>
{% endif %}
{% endblock %}

templates/library_view/book_detail.html
{% extends 'general_view/base.html' %}
{% load staticfiles %}
{% block st %}
<style>
.star {
    width:96px;
    height: 96px;
     background:url('{%static "img/hit.png" %}' );
       float:left;
}
.on {
      width:96px;
      height: 96px;
     background:url('{%static "img/yellow.png" %}');
}
.rated &gt; .rating {
      width:96px;
      height: 96px;
  background:url('{%static "img/yellow.png" %}');
}
</style>

{% endblock %}
{% block content %}
{%if book%}

<div class="col-lg-12 col-md-12 text-center">
        <br><br>
        <center><h2>{{book.name}}</h2></center>
        {% if user.is_authenticated%}
            {% if book.book_id in isFav %}
                <img src="{%static 'img/RedHeart.png' %}" width="2%" height="2%" id="makeFav" name="1" />
            {% else %}
                <img src="{%static 'img/Empty-Heart.png' %}" width="2%" height="2%" id="makeFav" name="2" />
            {% endif %}
        {%endif%}
        <br><br><br><br>
</div>

<div class="container">
     <div class="row">
         <div class="col-lg-12">
             <div class="row">
                 <div class="col-lg-3">
                     <img src="{{ book.picture.url }}"  alt="can't load image" width="160" height="170" class="img-responsive img-circle mt mb">

                 </div>
                 <div class="col-lg-9">
                     <p>Author: <a href="{% url 'library:AuthorDetail' book.Author.pk %}">{{ book.Author}}</a></p>
                     <p>Category: {% for category in categoryBooks %}
                        <a href="{% url 'library:CategoryDetail' category.pk%}">{{ category.name}}</a>
                     {% endfor %}
                     </p>
                     <p>published at: {{book.published_at}}</p>
                     <p>Country: {{book.country}}</p>
                     <p>Summary: {{book.summary}}</p>
                     <p><a class="btn btn-outline-warning" href="{{book.link}}">Read -></a></p>
                     {% if user.is_authenticated%}
                         <div>
                              {% if rateValue %}
                                  {% for i in rateValue %}
                                    <div class="star on rating"></div>
                                  {% endfor %}
                                  {% for i in non %}
                                    <div class="star"></div>
                                  {% endfor %}
                              {%else %}
                                    <div class="star"></div>
                                    <div class="star"></div>
                                    <div class="star"></div>
                                    <div class="star"></div>
                                    <div class="star"></div>
                              {% endif %}
                         </div>
                 </div>
             </div>
         </div>
         <button type="button" class="btn btn-outline-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                       Actions
         </button>
          <div class="dropdown-menu bg">
              {% if status == False %}
                <form method="POST" action="{% url 'library:add_to_wishlist' %}">
                    {% csrf_token %}
                    <input class="btn btn-outline-warning dropdown-item " type="submit"  name="add" value="add to wishList" />
                    <input class="btn btn-outline-warning" type="hidden" name="book_id" value="{{book.book_id}}" />
                </form>
              {% endif%}
              {% if status == True %}
                <form method="POST" action="{% url 'library:remove_from_wishlist' %}">
                    {% csrf_token %}
                    <input class="btn btn-outline-warning dropdown-item " type="submit"  name="remove" value="remove from wishList" />
                    <input class="btn btn-outline-warning" type="hidden" name="book_id" value="{{book.book_id}}" />
                </form>
              {% endif%}

             {% if book.book_id in isread %}
                <form method="POST" action="{% url 'library:deleteRead'%}">
                    {% csrf_token %}
                    <input class="btn btn-outline-warning dropdown-item" type="submit"  name="remove" value="Mark as unread" />
                    <input class="btn btn-outline-warning" type="hidden" name="book_id" value="{{book.book_id}}" />
                </form>
             {%else%}
                <form method="POST" action="{% url 'library:read'  %}">
                    {% csrf_token %}
                    <input class="btn btn-outline-warning dropdown-item" type="submit"  name="add" value="Mark as read" />
                    <input class="btn btn-outline-warning" type="hidden" name="book_id" value="{{book.book_id}}" />
                </form>
             {% endif %}
              </div>
          </div>
     {% endif%}

      <input type="hidden" id="book" value={{book}}>
      <input type="hidden" id="fav" value="{{isFav}}">
      <input type="hidden" id="isUser" value="{{isUser}}">
{% else %}
    <div class=""><center><h2>Something went wrong.</h2></center></div>
    <center><img src="{% static 'img/error.png' %}"  height="150" width="150"/></center>
{% endif %}
{% endblock %}
{% block js-foot %}
<script src="{%static 'js/jquery.min.js' %}"></script>
<script src="{%static 'js/book.js' %}"></script>
<script src="{%static 'js/jquery-1.4.2.min.js' %}"></script>
</div>
{% endblock %}

templates/library_view/book_list.html
{% extends 'general_view/base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="col-lg-12 col-md-12 text-center">
        <br><br>
        <center><h2>Books.</h2></center>
        <br><br><br><br>
    </div>
{% if book_list %}
    {% for book in book_list%}
    <div class="container">
        <div class="row">
              <div class="col-lg-12 col-lg-offset-3 col-md-12 ">
                  <img src="{{ book.picture.url }}" alt="can't load image" width="160"  height="170" class="img-responsive img-circle mt mb">
                  <pre></pre>
                  <a  href="{% url 'library:BookDetail' book.pk %}" >{{ book.name}}</a>
                  <pre></pre>
                  <pre></pre>
              </div>
        </div>
    </div>
    {% endfor %}
{% else %}
<div class=""><center><h2>There're no books yet.</h2></center></div>
<center><img src="{% static 'img/sad.png' %}"  height="150" width="150" /></center>
{% endif %}
{% endblock %}
    </div>

templates/library_view/category_detail.html
{% extends 'general_view/base.html' %}
  {% load staticfiles %}

{% block content %}

{%if category%}
<div class="col-lg-12 col-md-12 text-center">
        <br><br>
        <center><h2>{{category.name}}</h2></center>
        <img src="{{ category.picture.url }}" alt="can't load image" width="160" height="170" class="img-responsive img-circle mt mb">
        <br><br>
        {% if user.is_authenticated %}
          {% if category.category_id in isFav %}
            <img src="{%static 'img/RedHeart.png' %}" width="2%" height="2%" id="FavCat" name="1" />
          {% else %}
            <img src="{%static 'img/Empty-Heart.png' %}" width="2%" height="2%" id="FavCat" name="2" />
          {% endif %}
        {% endif %}
           <input type="hidden" id="category" value={{category.category_id}}>
        <br><br><br><br>
</div>
{%endif%}
{% if categoryBooks %}
  <div class="marg"><h2>Books</h2></div>
<br><br><br><br>

      {% for book in categoryBooks %}
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 col-lg-offset-3 col-md-12 ">
                            <img src="{{ book.picture.url }}" alt="can't load image" width="160" height="170" class="img-responsive img-circle mt mb">
                            <pre></pre>
                            <a href="{% url 'library:BookDetail' book.pk %}">{{ book.name}}</a>
                            <pre></pre>
                            <pre></pre>
                        </div>
                    </div>
                </div>
             {% endfor %}

<br><br><br><br>
{%else%}
<div class=""><center><h2>There're no books yet.</h2></center></div>
<br><br><br><br>
<center><img src="{% static 'img/sad.png' %}"  height="300" width="300" /></center>
{% endif %}
{% endblock %}
{% block js-foot %}
<script src="{%static "js/jquery.min.js" %}"></script>
<script src="{%static "js/category.js" %}"></script>
<script src="{%static "js/jquery-1.4.2.min.js" %}"></script>

{% endblock %}

templates/library_view/category_list.html
{% extends 'general_view/base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="col-lg-12 col-md-12 text-center">
        <br><br>
        <center><h2>Categories.</h2></center>
        <br><br><br><br>
    </div>
{% if category_list %}
    {% for category in category_list%}
    <div class="container">
        <div class="row">
              <div class="col-lg-12 col-lg-offset-3 col-md-12 ">
                  <img src="{{ category.picture.url }}" alt="can't load image" width="160" height="170" class="img-responsive img-circle mt mb">
                  <pre></pre>
                  <div class="categorymargin">
                      <a href="{%url 'library:CategoryDetail' category.pk%}">{{ category.name}}</a>
                    </div>
                  <pre></pre>
                  <pre></pre>
              </div>
        </div>
    </div>
    {% endfor %}
{% else %}
<div class=""><center><h2>There're no categories yet.</h2></center></div>
<center><img src="{% static 'img/sad.png' %}"  height="150" width="150" /></center>
{% endif %}
{% endblock %}

templates/library_view/index.html
{% extends 'general_view/base.html' %}

  {% load staticfiles %}
   {% block pic%}
       <a href="{% url 'user:home' %}"> <img src="{{ userp.picture.url }}" alt="can't load image" width="100" class="img-responsive img-circle mt mb"></a>
   {%endblock%}

{% block content %}
 <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="{% static 'img/thumb-1920-389875.jpg' %}"  height="500" alt="First slide"/>
        <div class="carousel-caption d-none d-md-block">
    <h5>Reads</h5>
    <p>It is a different reading experince</p>
  </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'img/1.jpg' %}"  height="500" alt="Second slide"/>
        <div class="carousel-caption d-none d-md-block">
    <h5>Books</h5>
    <p>find the latest Books</p>
  </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'img/2.jpg' %}" height="500" alt="Third slide"/>
        <div class="carousel-caption d-none d-md-block">
    <h5>Authors</h5>
    <p>Find and follow your favoutiate authors</p>
  </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev" >
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<h2>{{ b_number }}</h2>
<br><br><br>
  <h2><center>Categories</center></h2>
<p></p>
<br><br><br>
<div class="catindex">
    {%if categories%}

  {% for category in categories %}
        <img src="{{ category.picture.url }}" alt="can't load image" width="160" height="100" class="img-responsive img-circle mt mb">
        &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
        &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
  {% endfor%}
</div>
<p></p>
  {% for category in categories %}
    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
     <a href="{%url 'library:CategoryDetail' category.pk%}">{{ category.name}}</a>
    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  {% endfor%}
{%endif%}

<br><br>
<p></p>
  <a class="btn btn-outline-warning seemore" href="{% url 'library:CategoryList' %}">See More</a>
<p></p>
<br><br><br>
  <h2><center>Authors</center></h2>
<p></p>
<br><br><br>
<div class="catindex">
    {%if authors%}
      {% for author in authors%}
          <img src="{{ author.picture.url }}" alt="can't load image" width="200" height="150" class="img-responsive img-circle mt mb">
            &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
      {% endfor %}
    </div>
    <p></p>
      {% for author in authors%}
        &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          <a  href="{% url 'library:AuthorDetail' author.pk %}">{{ author.name}}</a>
        &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

      {% endfor %}
    {%endif%}
<br><br>
<p></p>
  <a  class="btn btn-outline-warning seemore" href="{% url 'library:AuthorList' %}">See More</a>
<p></p>
<br><br><br>
<h2><center>Recently added books.</center></h2>
<br><br><br>
<p></p>
<div class="catindex">
    {%if books%}
      {% for book in books%}
          <img src="{{ book.picture.url }}" alt="can't load image" width="200" height="150"  class="img-responsive img-circle mt mb">
      &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
      {% endfor %}
      </div>
      <p></p>
      {% for book in books%}
            &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
          <a href="{% url 'library:BookDetail' book.pk %}">{{ book.name}}</a>
            &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      {% endfor %}
    {%endif%}

<br><br>
<p></p>
  <a class="btn btn-outline-warning seemore" href="{% url 'library:BookList' %}">See More</a>
<p></p>
<br><br><br>

<h2><center>Funny Facts.</center></h2>
<br><br><br>
<figure class="figure1">
    <img src="{% static 'img/book.png' %}"  height="150" width="150" style="margin-left: 100px;"/>
    <img src="{% static 'img/feather.png' %}" height="150" width="150" style="margin-left: 200px;"/>
    <img src="{% static 'img/theater.png' %}" height="150" width="150" style="margin-left: 200px;"/>
    <img src="{% static 'img/reading.png' %}" height="150" width="150" style="margin-left: 200px;"/>
    <img src="{% static 'img/user.png' %}" height="150" width="150" style="margin-left: 200px;"/>
    <br><br>
    <div class="caption">
        <div class="book">
            Books<br><br>
            <div>{{book_no}}</div>
        </div>
        <div class="author">
            Authors<br><br>
            <div>{{author_no}}</div>
        </div>
        <div class="category">
            Categories<br><br>
            <div>{{category_no}}</div>
        </div>
        <div class="reader">
            Readers<br><br>
            <div>{{active_user}}</div>
        </div>
        <div class="user">
            Users<br><br>
            <div>{{users}}</div>
        </div>
    </div>
</figure>

{% endblock %}

templates/library_view/search.html
{% extends 'general_view/base.html' %}

{% block content %}
  <center><h2>Authors</h2></center>
<br><br><br><br>

  {% for author in authors%}
    <a href="{% url 'library:AuthorDetail' author.pk %}">
        <img style=float-left; src="{{ author.picture.url }}" alt="can't load image" width="120">
    </a>
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
      {% empty %}
     <center> <p>No authors with this name</p></center>
  {% endfor %}

<br><br><br><br>

  <center><h2>Books</h2></center>
<br><br><br><br>
  {% for book in books%}
    <a href="{% url 'library:BookDetail' book.pk %}">
        <img style=float-left; src="{{ book.picture.url }}" alt="can't load image" width="120">
    </a>
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
            &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
    {% empty %}
<center><p>No books with this name</p></center>
  {% endfor %}
 

{% endblock %}