community/urls.py
from . import views
from django.urls import path, re_path


app_name = 'community'

urlpatterns = [
    path('community/', views.home, name='home'),
    path('savequestion/', views.savequestion, name='savequestion'),
    re_path(r'^saveanswer/(?P<questionid>[0-9]+)$', views.saveanswer, name='saveanswer'),
]

django1/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from library import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('', include('library.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('', include('community.urls')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, re_path, include
from . import views
from django.contrib.auth import views as view

app_name = 'user'

urlpatterns = [
    re_path(r'^signup/$', views.sign_up, name='signup'),  # signup.
    re_path(r'^$', views.home, name='home'),
    re_path(r'^login/$', views.log_in, name='login'),
    re_path('logout', view.logout, {'next_page': 'login'}, name='logout'),
    re_path(r'^profile/(?P<Username>\w+)/$', views.profile, name='profile'),  # show other users profile.
    re_path(r'^search', views.search, name='search'),

]

templates/community_view/index.html
{% extends 'general_view/base.html' %}
{% block content %}
{% if user.is_authenticated %}
<div class="col-lg-12 col-md-12 text-center">
        <br><br>
        <center><h2>Welcome to community.</h2></center>
        <br><br><br><br>
</div>
<div class="size">
<h2>What's in your mind? </h2>
<div class="col-md-12 content-margin">
  <form class="form-horizontal style-form" action="{% url 'community:savequestion' %}" method="POST">
          {% csrf_token %}
        <div class="row">
            <div class="form-group">
                <div class="col-lg-12">
                <div class="input-group">
                    {{ QuestionForm.content }}
                    <span class="input-group-btn"><button class="btn btn-outline-warning" type="submit">Ask</button></span>
                </div>
              </div>
          </div>
        </div>
    </form>
<br><br><br><br>
    <div class="bord">
      {% for question in questions %}
      <div class="panel-heading">
        <div class="col-md-2">
            {% if question.user.is_superuser %}
                <p>Admin</p>
            {%else%}
            {% if user.get_username == question.user.username %}
            <a href="{% url 'user:home' %}">
                <img src="{{ question.user.profile.picture.url }}" alt="can't load image" width="160" height="170" class="img-responsive img-circle mt mb">
            </a>
            {% else %}
            <a href="{% url 'user:profile'  question.user.username %}">
                <img src="{{ question.user.profile.picture.url }}" alt="can't load image" width="160" height="170" class="img-responsive img-circle mt mb">
            </a>
            {% endif %}
            {% endif %}

        </div>
        <div class="media-body">
          <h4 class="media-heading">{{ question.user.username}}</h4>
          <p class="media-usermeta">
            <span class="media-time">{{ question.posted_time }}</span>
          </p>
        </div>
      </div>
      <div class="panel-body">
      <div class="media">
        <div class="media-body">
          <p>{{question.content }}</p>
          <br>
        </div>
      </div>
      </div>
      <div class="panel-footer">
      <ul class="list-inline">
        <li><a data-target="#{{question.question_id}}" data-toggle="collapse"><i class="glyphicon glyphicon-comment"></i> Comments ({{question.number_of_answers}})</a></li>
      </ul>
      </div>

      <div class="collapse panel-footer" id="{{question.question_id}}">
      <ul class="media-list">
          {% for answer in answers %}
          {% if question.question_id == answer.question_id.question_id%}
        <li class="media">
          <div class="col-md-2">
              {% if answer.user.is_superuser %}
                 <p>Admin</p>
            {%else%}
            {% if user.get_username == question.user.username %}
            <a href="{% url 'user:home' %}">
                <img src="{{ answer.user.profile.picture.url }}" alt="can't load image" width="160" height="170" class="img-responsive img-circle mt mb">
            </a>
            {% else %}
            <a href="{% url 'user:profile'  answer.user.username %}">
                <img src="{{ answer.user.profile.picture.url }}" alt="can't load image" width="160" height="170" class="img-responsive img-circle mt mb">
            <a href="{% url 'user:profile' question.user.username %}">
            <img alt="" src="{{ question.user.profile.picture.url }}" class="media-object img-responsive">

            </a></a>
              {% endif %}
              {% endif %}

          </div>
          <div class="media-body">
            <h4 class="media-heading">{{ answer.user.username }} <small>{{ answer.posted_time }}</small></h4>
          <p>{{answer.content }}</p>
          </div>
        </li>
          {% endif %}
          {% endfor %}
      </ul>
      </div>

      <form  action="{% url 'community:saveanswer' question.question_id %}" method="POST"  class="panel-footer">
          {% csrf_token %}
          <div class="row">
            <div class="form-group">
                <div class="col-lg-12">
                <div class="input-group">
                  {{ AnswerForm.content }}
                    <span class="input-group-btn"><button class="btn btn-outline-warning" type="submit">Comment</button></span>
                </div>
              </div>
          </div>
        </div>
      </form>
      {% endfor %}
  </div>
    </div>
</div>
{% endif %}
{% endblock %}